<?php

/**
 * @file
 * integrarte_glue.module
 */
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_form_alter().
 */
function integrarte_glue_form_alter(&$form, &$form_state, $form_id) {
 //dpm($form);
 //dpm($form_id);
 if ($form_id == 'node_application_form') {
   //dpm($form['field_online_video']);
   $form['field_online_video']['widget'][0]['#markup'] = $form['field_online_video']['widget'][0]['#description'];
   $form['actions']['submit']['#submit'][] = 'integrarte_glue_application_submit'; 
   $form['actions']['submit']['#value'] = t('Submit application'); 	
   																		
 }
 
 if ($form_id == 'profile_main_edit_form') {
 	//dpm('personal information form');
 }

}

function integrarte_glue_application_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    //drupal_set_message('we sent a form woohoo');
    $form_state->setRedirect('integrarte_glue.application_submitted');
}

function integrarte_glue_node_presave(EntityInterface $node) {
    //dpm($node->toArray());
    if ($node->type->target_id == 'application') {
    	//dpm($user->toArray());
			// get the author's username
			$author_uid = $node->uid->target_id;
			$account = \Drupal\user\Entity\User::load($author_uid); // pass your uid
			$name = $account->getUsername();
	    $node->title->value = 'Summer Application: ' . $name;
    }
}