<?php

/**
 * @file
 * integrarte_glue.module
 */
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_form_alter().
 */
function integrarte_glue_form_alter(&$form, &$form_state, $form_id) {
 //dpm($form);
 //dpm($form_id);
 if ($form_id == 'node_application_form') {
   //dpm($form['field_online_video']);
   $form['field_online_video']['widget'][0]['#markup'] = $form['field_online_video']['widget'][0]['#description'];
   $form['actions']['submit']['#submit'][] = 'integrarte_glue_application_submit'; 
   $form['actions']['submit']['#value'] = t('Submit application'); 	
   																		
 }
 
  if ($form_id == 'node_registration_form') {
   $form['actions']['submit']['#submit'][] = 'integrarte_glue_registration_submit'; 
   $form['actions']['submit']['#value'] = t('Submit registration'); 	
   																		
 }
 
 if ($form_id == 'profile_main_edit_form') {
 	//dpm('personal information form');
 }

}

function integrarte_glue_application_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    //drupal_set_message('we sent a form woohoo');
    $form_state->setRedirect('integrarte_glue.application_submitted');
}

function integrarte_glue_registration_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    //drupal_set_message('we sent a form woohoo');
    $form_state->setRedirect('integrarte_glue.registration_submitted');
}

function integrarte_glue_node_presave(EntityInterface $node) {
    //dpm($node->toArray());
    if ($node->type->target_id == 'application') {
    	//dpm($user->toArray());
			// get the author's username
			$author_uid = $node->uid->target_id;
			$account = \Drupal\user\Entity\User::load($author_uid); // pass your uid
			$name = $account->getUsername();
	    $node->title->value = 'Summer Application: ' . $name;
    }
    
    if ($node->type->target_id == 'registration') {
    	//dpm($user->toArray());
			// get the author's username
			$author_uid = $node->uid->target_id;
			$account = \Drupal\user\Entity\User::load($author_uid); // pass your uid
			$name = $account->getUsername();
	    $node->title->value = 'Summer Registration: ' . $name;
    }
}

/**
* Implements hook_mail().
*/
function integrarte_glue_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'create_application':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('@title', array('@title' => $params['subject']), $options);
     $message['body'][] = $params['message'];
     break;
 }
}

/**
 * Implements hook_mail_alter().
 */
function integrarte_glue_mail_alter(&$message) {
  switch ($message['key']) {
    case 'node_insert':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      break;
  }
}

/**
* Implements hook_entity_insert().
*/
function integrarte_glue_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

 if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'application')) {
   return;
 }
 $mailManager = \Drupal::service('plugin.manager.mail');
 $module = 'integrarte_glue';
 $key = 'create_application';
 $system_site_config = \Drupal::config('system.site');
 $to = $system_site_config->get('mail');

 // Load the current user.
 $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
 $first = $user->get('field_first_name')->value;
 $last = $user->get('field_last')->value;
 
 $nid = $entity->get('nid')->value;
 $options = ['absolute' => TRUE];
 $url = \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $nid], $options);
 $url = $url->toString();

 $params['message'] = '<p>Name: ' . $first . ' ' . $last . '</p>' . 
 										  '<p>Notes: ' . $entity->get('field_notes')->value . '</p>' .
 										  '<p>View Application: ' . $url . '</p>' ;
 $params['subject'] = t('Summer Application Submitted: ') . $first . ' ' . $last;
 $params['node_title'] = $entity->label();
 $langcode = \Drupal::currentUser()->getPreferredLangcode();
 $send = true;
 $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
 if ($result['result'] !== true) {
   drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
 }
 else {
   drupal_set_message(t('Your message has been sent.'));
 }
}